//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dboConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int id { get; set; }
        public int ToUser { get; set; }
        public int TypeTask { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string TitleTask { get; set; }
        public Nullable<int> FromUser { get; set; }
        public string SubjectTask { get; set; }
    }
}
